### ISSUE TITLE
Player is not on top of the floor, it is a bit in the floor 

### ISSUE THREAD

**Issue by hmyeh** [NilsHullegien/TempleRunGroup5#14]

**Comment by mwolting** [comment]
Fixed in pull request #3

**Comment by levilime** [comment]
It's not fixed... If I for example open the task manager there is a big interval where the block still drops through the floor, also if I put the gravity higher (order of 50) the block falls through the floor at the initial startup. This is something that can be fixed at a later stage and is not for the Prototype milestone.
